package ${servicePackage}.${implPath};

import ${servicePackage}.${entityName}Service;
import ${daoPackage}.${entityName}Dao;
import org.springframework.stereotype.Service;

import javax.annotation.Resource;

/**
 * Generated by Code-Generator.
 * Author: ProgrammerRabbit
 * http://github.com/ProgrammerRabbit
 */
@Service
public class ${entityName}Service${upperCaseImplPath} implements ${entityName}Service {
    @Resource
    private ${entityName}Dao dao; // TODO rename this


}
