package com.github.programmerrabbit.dao;

import com.github.programmerrabbit.entity.User;
import com.github.programmerrabbit.test.Demo;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import java.util.List;

/**
 * Generated by Code-Generator.
 * Author: ProgrammerRabbit
 * http://github.com/ProgrammerRabbit
 */
@Demo
public interface UserDao {
    void insert(@Param("entity") User entity);

    @Select("SELECT * FROM User WHERE id = #{id}")
    User getById(@Param("id") int id);

    @Select("SELECT * FROM User WHERE #{fieldName} = #{fieldValue}")
    List<User> getByField(@Param("fieldName") String filedName, @Param("fieldValue") Object fieldValue);

    void updateById(@Param("id") int id, @Param("entity") User entity);

    @Delete("DELETE FROM User WHERE id = #{id}")
    void deleteById(@Param("id") int id);
}